### ISSUE TITLE
What should I be returning from egress?

### ISSUE THREAD

**Issue by AxeOfMen** [sleelin/scimmy-routers#11]
Here's some pseudocode describing what I'm doing in my Users.egress function:

```js
async (resource) => {
  let users = await GetUsersByFilter(resource.filter);
  // convert my user objects to SCIMMY User resources...
  users = users.map(user => new SCIMMY.Resources.User({
        externalId: user.externalId,
        userName: user.upn,
        displayName: user.name,
        active: true,
        emails: [{
          value: user.email,
          type: "work",
          primary: true,
        }],    
  }));
  return users;
}
```

1) When this egress function returns an empty array, scimmy-routers responds to the client with http status 400, Bad Request.
2) When this egress function returns a non-empty array, scimmy-routers responds to the client with http status 500, Internal Server error (but no error is thrown in my egress function)

What should my egress function be returning?

**Comment by sleelin** [comment]
Hi @AxeOfMen,

In answer to your question, the egress method should always return an array of objects, each with properties whose names match the attribute names defined by the resource's schema - in this case the User schema. Of particular note is that if _any_ of the objects is missing a required attribute, the request will fail, as the resulting value (or values) would no longer conform to the schema. On closer inspection I can see how the documentation for the ~gress methods hasn't really made this clear, and will work on updating it and providing a few more usage examples.

The specifics of what the [user resource's read method](https://github.com/scimmyjs/scimmy/blob/7cd3145c6b6af4139af4c9ecfa7be17664ef5500/src/lib/resources/user.js#L75) does with the return value of the egress method mean that it's not necessary to instantiate new resources for each object before returning the users. Instantiation (and consequently, validation) of the user (or group) resources is done by the read method before it returns to the express router to respond to the request. With that in mind, the pseudocode for the egress handler would change to look more like the following:
```js
async (resource) => {
    // Get the user resources from your data source (e.g. a database of some kind)
    const users = await GetUsersByFilter(resource.filter);
    
    // Map each database field to their corresponding SCIM attribute...
    return users.map(user => ({
        // ...being sure to include the required 'id' and 'username' attributes
        id: user.id,
        userName: user.upn,
        // ...and any other attributes that the service provider will support
        externalId: user.externalId,
        displayName: user.name,
        active: true,
        emails: [{
            value: user.email,
            type: "work",
            primary: true
        }]
    }));
}
```

> [!NOTE]
> The `id` attribute is always required in the resulting resource, even when the request is for a resource with a specific id.
> The value of the `id` attribute should be universally unique (i.e. not the same as the value of the `externalId` attribute), and should be generated by your service provider at the time the resource is created.

Think of the `SCIMMY.Resource` classes as analogous to "controllers" in the MVC software design pattern (with the scimmy-routers express routes being the "views", and the `SCIMMY.Schemas` classes being the "models"). The resource classes are responsible for orchestrating the overall details of a request (i.e. is this request for a specific resource, or a list of resources? Are any attributes to be excluded? Was there a filter included in this request? If the request was for a list of resources, were any sorting or pagination details included?).

I hope this explanation provides some more clarity for you, please let me know if you have any further questions.

Thanks,
Sam
