### ISSUE TITLE
Use peer dependencies?

### ISSUE THREAD

**Issue by fflorent** [sleelin/scimmy-routers#20]
Hi,
First of all, thank you very much for your work!

## Context

Express is used as a direct dependency, which means it is installed by both the host and the middleware.

Let's imagine that the host has express installed in version 4.18.2, it would have these dependencies installed:
```
├── express@4.18.2
└─┬ scimmy-routers@1.2.1
  └── express@4.19.2
```

Express would be installed twice, with all the drawbacks it has (`node_modules` bigger, having to worry about both of the express versions, etc.).

## Proposed solution

Peer Dependencies are meant to solve this issue in most of the cases. This blog post explains that well, and exposes the example of express middlewares as one of the use case for them:
https://nodejs.org/en/blog/npm/peer-dependencies

And for the tests, you still may install express as a `devDependencies`.

I am less sure, but I also wonder if that could not also be useful for Scimmy. The host is expected to install this dependency directly too, right?

**Comment by sleelin** [comment]
Hi @fflorent, thanks for raising this!
It seems like the `peerDependencies` functionality is designed exactly for this use case.

I've now merged a PR that moves the express and scimmy dependencies to the `peerDependencies` section in package.json, and this change will be available in the next release.

Thanks,
Sam
