### ISSUE TITLE
getting invalidSyntax error

### ISSUE THREAD

**Issue by smali-kazmi** [sleelin/scimmy-routers#31]
i had implemented filter in egress if i return single user object then it works fine otherwise in case of list response i am getting following error

**Error:**
```js
{
  schemas: [ 'urn:ietf:params:scim:api:messages:2.0:Error' ],
  status: '400',
  scimType: 'invalidSyntax',
  detail: 'The request body supplied a schema type that is incompatible with this resource'
}
```

**Route:** 
```HTTP
GET /api/v2/entities/1/scim/Users?filter=id+gt+3&startIndex=1&count=10
```

**Response:**

```js
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:ListResponse"
  ],
  "totalResults": 3,
  "startIndex": 1,
  "itemsPerPage": 3,
  "Resources": [
    {
      "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
      ],
      "id": "4",
      "userName": "Chelsie_Yost",
      "name": {
        "formatted": "Giovanna Schumm",
        "familyName": "Schumm",
        "givenName": "Giovanna"
      },
      "emails": [
        {
          "value": "***@gmail.com",
          "primary": true
        }
      ],
      "active": true,
      "meta": {
        "resourceType": "User",
        "created": "2024-12-12T17:34:03.000Z",
        "lastModified": "2024-12-12T17:34:03.000Z",
        "location": "/api/v2/entities/1/scim/v2/Users/4"
      }
    },
 .... 
 ....
    
  ]
}
```

**Comment by sleelin** [comment]
Hi @smali-kazmi,
If I'm understanding the issue correctly, the **Response** snippet is your expected response, and the **Error** snippet is the actual response you receive?

Could you please let me know which versions of the `scimmy` and `scimmy-routers` packages you're using?

My initial suspicion is that your egress handler may be unnecessarily including the schemas attribute on the user object, and that the value doesn't exactly match the expected user schema ID, as this is what causes that specific error response.
Could you please provide some sample code for your egress handler that reproduces the issue?

Thanks,
Sam

**Comment by smali-kazmi** [comment]
thank you so much @sleelin for the reply really appreciate it yes error snappit is the actually i got in response

**Scimmy versions** 
```
    "scimmy": "^1.2.4",
    "scimmy-routers": "^1.2.2",
```

let me share all my code snapit with you

**Routers file**
```js
const express = require('express');
const { default: SCIMMYRouters, SCIMMY } = require('scimmy-routers');
const controller = require('controllers/scim');
const { ScimError } = require('helpers/scim');

const router = express.Router({
  mergeParams: true,
});

const verifyAuth = async (req) => {
  return true
};

SCIMMY.Resources.declare(SCIMMY.Resources.User)
  .ingress(controller.manageUser)
  .egress(controller.getUser)
  .degress(controller.deactivateUser);

SCIMMY.Resources.declare(SCIMMY.Resources.Group)
  .ingress((resource, data) => {
    console.log(
      `Request to create/edit group ${resource}, `,
      JSON.stringify(resource, null, 2),
      JSON.stringify(data, null, 2)
    );
  })
  .egress((resource) => {
    console.log(`Request to read group ${resource}`);
  })
  .degress((resource) => {
    console.log(`Request to delete group ${resource}`);
  });

router.use(
  '/',
  new SCIMMYRouters({
    type: 'bearer',
    docUri: 'https://example.com/help/oauth.html',
    // Your handler for verifying authentication status of a request
    handler: verifyAuth,
    // Optionally, some method to provide additional context to requests...
    context: async (req) => {
      const locationId = req.orgConfig.scimDefaultLocationId;
      const integration = {id: 1};

      return {
        refId: `refId:${new Date().getTime()}`,
        resourceId: id,
      };
    },
  })
);
module.exports = router;
```

**Controller Action**
```js

exports.getUser = async (resource, data) => {
  try {
    
    let response = null;
    if (resource.id) {
      const user = await UserModel.getUserDetailsById(resource.id, data.entityId);
      response = ScimDecorator.decorateUser(user);
    } else {
      const userList = await UserModel.filterUsers(filters);

      //Don't throw error if return only one user
      response = userList.length ? ScimDecorator.decorateUser(userList[0]) : null; // don't throw error
      
      //Throw error if return list of user
      response = ScimDecorator.decorateListResponse(userList)
    }

    // console.log('---response', JSON.stringify(response, null, 2));

    if (!response) {
      throw new ScimError(httpStatus.NOT_FOUND, 'User (s) not found');
    }

    return response;
  } catch (error) {
    throw new ScimError(httpStatus.INTERNAL_SERVER_ERROR, error.message);
  }
};
```

**Comment by sleelin** [comment]
Thanks for following up @smali-kazmi. It looks like your routers are set up correctly, but I'm still not entirely sure what's happening in your controller code. What are the `ScimDecorator.decorateUser` and `ScimDecorator.decorateListResponse` methods doing, and what is the `ScimError` class?

If I'm guessing correctly, you're using them to structure the returned objects as fully formed SCIM responses? If so, you might have misunderstood that the SCIMMY library is designed to do all of the heavy lifting of formatting the responses for you. When retrieving one user, your egress method should be returning a single object without the additional SCIM protocol properties (i.e. the `schemas` property). When retrieving multiple users for a list response, your egress method should be returning an array of these objects - not a fully formed list response - as the contents of the array are used by SCIMMY to generate the correct list response message. If you haven't already, please see the [egress handler section](https://scimmyjs.github.io/SCIMMY.Types.Resource.html#~EgressHandler) of the SCIMMY documentation, as it has an example that also covers error handling.

Regarding the specific error response, for user resources, it is thrown when a user object contains a `schemas` property with at least one value, but does not include the mandatory string value of `"urn:ietf:params:scim:schemas:core:2.0:User"`, which is the SCIM schema ID for user resources. If you are including a `schemas` property on your user objects, please make sure it is an array of strings, and that it includes this mandatory string value. Alternatively, you could instead remove the `schemas` property, as it will be automatically added by SCIMMY with the correct values.

Thanks,
Sam

**Comment by smali-kazmi** [comment]
@sleelin you are awesome! it is the same issue `decorateListResponse` was returning formatted response when i just return user from it; has fixed the issue!

**Comment by smali-kazmi** [comment]
small appreciation of $20 from my side closing this issue

**Comment by sleelin** [comment]
Thanks @smali-kazmi, much appreciated!
