### ISSUE TITLE
Support for multi-tenant identifiers in URLs?

### ISSUE THREAD

**Issue by jonathanstokes** [sleelin/scimmy-routers#7]
I'd like to support multiple tenants from the same server, and initially was planning to do that with a URL pattern like:

```
/api/admin/<tenant-id>/scim/Users
/api/admin/<tenant-id>/scim/Groups
…
```

This makes it clear from the URL which tenant is making the request, which seems cleaner that determining the tenant from a bearer token or something similar.

Setting up the Express routes this way has worked fine for me. However, it seems like the underlying resources set their `basepath` once and never again, which means that my responses all have paths from the first tenant to call, no matter which tenant requests them.  The private variables make it impossible (afaik) to override or reset them.

Has this been done before?  Is there any other approach I should take to meet this requirement?

**Comment by sleelin** [comment]
Hi Jonathan,
I believe this should now be possible in v1.0.0 of SCIMMY as resource basepaths are no longer write-once.

Thanks,
Sam
